//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqOracle.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JK_PM_MES_CTD
    {
        public string CTD_NO { get; set; }
        public string SJD_NO { get; set; }
        public string CO_TYPE { get; set; }
        public string ITEM_SETUP_NO { get; set; }
        public string ITEM_TYPE { get; set; }
        public string ROOM_TYPE { get; set; }
        public Nullable<decimal> SET_QTY { get; set; }
        public string BIAO_DUAN { get; set; }
        public string LOU_NO { get; set; }
        public string LOU_UNIT { get; set; }
        public string LOU_CENG { get; set; }
        public string ROOM_NO { get; set; }
        public string BILL_STATUS { get; set; }
        public decimal ID { get; set; }
        public string NEED_DATE { get; set; }
        public string ITEM_SETUP_NAME { get; set; }
        public string FIX_DATE { get; set; }
        public string PROJ_TYPE { get; set; }
        public string SPLIT_ORDER_TYPE { get; set; }
    }
}
